### ISSUE TITLE
 error: <class 'socket.error'>

### ISSUE THREAD

**Issue by BowgartField** [n-y-z-o/nyzoVerifier#13]
Hello,
I have got a error when i triy to execute the command "supervisor reload".

The entire error is :

`error: <class 'socket.error'>, [Errno 2] No such file or directory: file: /usr/lib/python2.7/socket.py line: 228`

I'm running this into a ubuntu docker container.

Thank

**Comment by daveybrown** [comment]
There are a couple of things. In docker don't run commands as sudo un-necessarily.

And

```
touch /var/run/supervisor.sock
chmod 777 /var/run/supervisor.sock
service supervisor restart
```

before `sudo supervisorctl reload`

### ☮️

**Comment by BowgartField** [comment]
> There are a couple of things. In docker don't run commands as sudo un-necessarily.
> 
> And
> 
> ```
> touch /var/run/supervisor.sock
> chmod 777 /var/run/supervisor.sock
> service supervisor restart
> ```
> 
> before `sudo supervisorctl reload`
> 
> ### ☮️

Thank you so much but now I got a new error: 
`error: <class 'socket.error'>, [Errno 111] Connection refused: file: /usr/lib/py            thon2.7/socket.py line: 228
`

**Comment by daveybrown** [comment]
What about this... 

```
touch /var/run/supervisor.sock
chmod 777 /var/run/supervisor.sock
service supervisor restart
service supervisor start
supervisorctl reload
supervisorctl status
```

I'm in #help on discord if you want to speak there for 5 mins.

**Comment by BowgartField** [comment]
i'm trying this. what's the discord
