### ISSUE TITLE
Edit website to declare Nyzo support on Citex.co.kr

### ISSUE THREAD

**Issue by brainwave-bruteforce** [n-y-z-o/nyzoVerifier#16]
as the title says, the coin is supported on citex and has a lot more volume than on qtrade.

**Comment by n-y-z-o** [comment]
Citex.co.kr does not appear to be a valid, functioning site. Attempting to navigate the site to find where Nyzo might be listed, a number of very odd SSL errors and 404s were encountered. These issues have persisted for several days.

If the site is able to resolve its issues, posting of a link on nyzo.co will be reconsidered.
