### ISSUE TITLE
Broken Sentinel voting

### ISSUE THREAD

**Issue by orisica** [n-y-z-o/nyzoVerifier#24]
As reported numerous times by numerous users on Nyzo Discord, sentinel voting doesn't work at all on latest versions. 
Latest known version that works is v587.

Can you fix voting so that verifier operators are able to cast their votes for pressing issues?

**Comment by kevinchartier** [comment]
You note that the latest known version to work is v587. If you review the release notes for v588 (https://tech.nyzo.co/releaseNotes/v588), you will find the following statement (bold preserved from the release notes, speaking of `BlockManager`):

> Also, the static block has been removed. This is a significant, far-reaching change. **This change has been fully tested for the verifier, sentinel, and client, but it may still have some unintended effects on scripts.** This will continue to be reviewed.

In the interest of encouraging community involvement in the code, can anyone suggest a one-line change that would restore behavior of the script at v588 and above to the same behavior that was present at v587 and before?

**Comment by n-y-z-o** [comment]
https://tech.nyzo.co/releaseNotes/v597
