### ISSUE TITLE
v484 issue after VPS restart

### ISSUE THREAD

**Issue by reb0rn21** [n-y-z-o/nyzoVerifier#3]
Update to v484 is fine, but if VPS on v484 is restarted (for upgrade, maintenance...) the time needed for verifier to recover from yellow state to white is over 5 hours
Verifier is very slow to connect to mash and rate is 2-3 connections per minute

**Comment by n-y-z-o** [comment]
This issue was corrected in version 487 with the supplemental connection process before starting the main verifier loop.  https://nyzo.co/releaseNotes/487
