### ISSUE TITLE
Remove and add exchange On https://nyzo.co/coins

### ISSUE THREAD

**Issue by cgouh** [n-y-z-o/nyzoVerifier#34]
Remove Bihodl
Add Bilaxy https://bilaxy.com/trade/NYZO_USDT
Add Hotbit https://www.hotbit.io/exchange?symbol=NYZO_USDT

**Comment by n-y-z-o** [comment]
Done. Thank you!

**Comment by cgouh** [comment]
Thank you for your update.
Btw, another 2 exchange have listed NYZO.
Gate: https://www.gate.io/en/trade/NYZO_USDT
Hoo: https://hoo.com/spot/nyzo-usdt

**Comment by n-y-z-o** [comment]
Thank you! Just added these, too.
