### ISSUE TITLE
new node can 't find in queue page

### ISSUE THREAD

**Issue by neicedai** [n-y-z-o/nyzoVerifier#48]
I had built a few new nodes but I can not find them in queue page

**Comment by n-y-z-o** [comment]
Please email the IP addresses of these nodes to nyzo@nyzo.co, and we'll look at them to see if we can find the issue. We'll post a follow-up here when the issue has been resolved.

**Comment by n-y-z-o** [comment]
This has been resolved.

If anyone else is unable to see their verifier in the queue page, checking your verifier by IP address from the client is a good first troubleshooting step.

https://client.nyzo.co/verifierStatus

If you do not receive a response, but your verifier seems to be running properly, you should check your firewall to make sure port 9444 is open to TCP and 9446 is open to UDP.

When you do receive a response from the client status check, be sure that the verifier indicates it is receiving UDP.

![nyzo-client-good-response](https://github.com/n-y-z-o/nyzoVerifier/assets/34757259/b456ea37-30bf-4040-b97c-84a81bba1a05)

If the client status check looks good, your verifier should eventually show up in the queue. Verifiers regularly send node-join messages to in-cycle verifiers to announce their presence. If you want to speed up the process, restart your verifier. When a verifier is restarted, it sends some additional node-join messages that will cause it to appear more quickly.
