### ISSUE TITLE
NO PRIVATE KEY FLIE

### ISSUE THREAD

**Issue by q3579338** [n-y-z-o/nyzoVerifier#5]
root@choosefabric:/var/lib/nyzo/production# ls -a
.  ..  nickname  trusted_entry_points

more /var/lib/nyzo/production/verifier_private_seed
more: stat of /var/lib/nyzo/production/verifier_private_seed failed: No such file or directory

**Comment by hclivess** [comment]
Did you actually run the node yet?

**Comment by jimtalksdata** [comment]
Since you are on root, check nyzoVerifier.conf to see if the path to the jar file is correct. If not, change it and reload.

**Comment by hclivess** [comment]
I suggest closure
